### PR TITLE
Automated dependency upgrades

### PR DESCRIPTION
**Pull request by hc-github-team-secure-vault-ecosystem**
Full log: https://github.com/hashicorp/vault-plugin-database-elasticsearch/actions/runs/9162826824

  IMPROVEMENTS:
* Updated dependencies:
   * `github.com/hashicorp/go-retryablehttp` v0.7.5 -> v0.7.6
   * `github.com/hashicorp/vault/sdk` v0.11.0 -> v0.12.0
   * `github.com/stretchr/testify` v1.8.4 -> v1.9.0

### CODE REVIEW

**Comment by hc-github-team-secure-vault-core** [comment]
Vault CI check PR: https://github.com/hashicorp/vault/pull/26217

**Comment by hc-github-team-secure-vault-core** [comment]
Vault CI check PR: https://github.com/hashicorp/vault/pull/26217

**Comment by hc-github-team-secure-vault-core** [comment]
Vault CI check PR: https://github.com/hashicorp/vault/pull/26217

**Review by Zlaticanin — APPROVED** [review]

**Comment by hc-github-team-secure-vault-core** [comment]
Vault CI check PR: https://github.com/hashicorp/vault/pull/26217

**Pull request merged**
